### ISSUE TITLE
Use of _ in naming variables attached to ListView

### ISSUE THREAD

**Issue by patrickckelly** [vecnatechnologies/backbone-torso#100]
I am attempting to make an extension of ListView but problems arise because some of the variables are assigned to View._variableName

This is some sample working code I have
initialize: function(options){

options.collection = this.createPrivateCollection(secureMessageCollection)
this.collection = options.collection
Torso.ListView.prototype.initialize.call(options)
}

I would rather just be able to do,
this.collection = this.createPrivateCollection(secureMessageCollection)

**Comment by mandragorn** [comment]
on the 0.1.x branch and master add the || logic to ListView for arg properties (specifically _collection).  On master this._collection was removed.

**Comment by mandragorn** [comment]
0.2.x + is consistent and no one should be on 0.1.x going forward.
