### ISSUE TITLE
ListView never calls activate

### ISSUE THREAD

**Issue by patrickckelly** [vecnatechnologies/backbone-torso#101]
ListView never calls the activate function

View does it in it's initialize but ListView only calls View's super();

Should ListView be calling activate in it's initialize or should super() be calling activate?

**Comment by kentmw** [comment]
On master, or 0.2.0, activate will be called immediately after initialize method finishes automatically. You will not need to invoke activate.

**Comment by mandragorn** [comment]
on 0.1.x add activate() to initialize() of ListView.

**Comment by kentmw** [comment]
This was solved by https://github.com/vecnatechnologies/backbone-torso/pull/148
