### ISSUE TITLE
FormModel doesn't save unless tracking a model

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#111]
For a form model that is merely a way to push multi-object updates (meaning it's using the "url" field), it's not strictly necessary that the form model pushes/pulls from an object model.

I had to add:
```
this.model.addModel({model: myObjectModel, fields: []});
```
before saving.

This does pose the question, am I using the Form Model incorrectly? Should I just create a model to represent this new save? The counter-argument to that is that I want form model to bind to the DOM with data-model and I want to push to a different url. Why would I have to create both a new FormModel and a Model to do that?

**Comment by stonecalvin** [comment]
So far I have only used form models in that way. It feels like an effect of being able to track multiple models via the form model. Perhaps we should have two options, one single-model backed form model (or just the form model itself) and then a possible collection of models backed form model for advanced usage?

**Comment by kentmw** [comment]
I think that the distinction we're trying to create is between tracking any models or no models. We only threw in that catch because we couldn't think of a reason why you would want to save if it wasn't tracking (previously, the only way to save was to invoke save on the models). Now that we can save the form model itself, blocking the save invocation because its not tracking models seems silly.

**Comment by kentmw** [comment]
https://github.com/vecnatechnologies/backbone-torso/pull/154 fixes this
