### ISSUE TITLE
Has anyone figured out how to animate a transition from one template render to another?

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#123]
If I produce one set of html to another across two renders and the second render takes up more space, let's say, I want to know how to animate that transition. As in, I'd like the container div to expand.

This probably could be solved many different ways, potentially not using render at all, but I was curious if others have wanted/tried this before.

**Comment by kentmw** [comment]
As of now, I'm just rendering all new content with hidden classes, then animating them in after render is complete

**Comment by arikwex** [comment]
This is considered a standard approach.
If you look at angularJS for the ngAnimate support, you'll see that they do the same thing.
There is lots of voodoo magic in angular, but it pretty much listens for when CSS animations are done before removing the old element.  When a transition happens there is a sequence of CSS class triggers:
1) .ng-enter is placed on the newly entering DOM
2) .ng-leave is placed on the current DOM
3) .ng-enter.ng-enter-active is placed on the new DOM
4) .ng-leave.ng-leave-active is place on the current DOM

This should handle your animation start and stop states.  The hard part is definitely just how to hook in to the "When is the CSS animation done."

**Comment by kentmw** [comment]
The new transitions code allows for all of the css class additions (they don't happen by default, but are if we find that all transitions follow this same behavior, we can roll that in by default). It also allows for custom javascript play as well.

Currently, we're letting the developers dictate "when the css animation is done". Matt's looking into how to track css animation completions generically.
