### ISSUE TITLE
No way to fetch subset of models from collection

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#124]
I have a cache collection and a few private/requester collections. When I add new ids I care about, I either have to fetch the entire cache, or the entire requester collection that added new ids. The requester collection could have ~1000 models in it and I've only added a few but am forced to fetch the entire set of models.

Currently, to get around this, I have to manually find the newly added ids and create a temporary requester collection and then remove it after making the fetch.

```
var idsOfModelsNeedingFetching = _.difference(newIds, requesterCollection.pluck('id'));
var tempRequester = cache.createPrivateCollection('temporary');
tempRequester.trackIds(idsOfModelsNeedingFetching);
tempRequester.fetch().always(function() {
  tempRequester.requesterDispose();
});
```

**Comment by mandragorn** [comment]
+1 - I feel like the cache / requestor (private) collection framework could use some love in general.  I think these are captured elsewhere, but wanted to make sure I write them down before I forget.
1) I want to track a single model, a private collection seems like overkill, would be nice to have the same idea (maybe as a service) that is explicit about being for a single model.
2) Lazy fetching - only fetch models of new ids when they are added (this is currently broken).
3) This issue (kind of a subset of 2) - only fetch new ids added to the requestor collection.

**Comment by kentmw** [comment]
I feel like most of the issues are missing API. Perhaps we can come up with a set of API additions and create an enhancement issue for it.

**Comment by mandragorn** [comment]
I would like that so that we can think about the requestor / cache API as a whole.

**Comment by kentmw** [comment]
We can add:

```
fetchSubsetOfTrackedIds: function(ids) {
  var subsetOfTrackedIds = // the intersection of the ids and requesterCollection.trackedIds;
  return parentInstance.fetchByIds({idsToFetch: subsetOfTrackedIds, setOptions: {remove: false}});
}
```

and 

```
pull: function() {
  // var idsNotTracked = find ids that we don't have in cache;
  return parentInstance.fetchByIds({idsToFetch: idsNotTracked, setOptions: {remove: false}});
}
```
