### ISSUE TITLE
requester collection addModelAndTrack needs to add model to parentInstance

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#125]
It adds the model to the requester collection just fine and even tracks the new id to the parent instance. But it should also add the model to the cache as well.

**Comment by mandragorn** [comment]
side note - I'm just learning of the addModelAndTrack() method which sounds like it should be used in the cases of creating a new model to save.  Earmark as something that needs to make it into the documentation.

side side note - what is the status of getting code documentation (yuidocs) accessible from github?

**Comment by kentmw** [comment]
Currently, addModelAndTrack takes an existing model that has an id already to the requester/cache pair. 

Good question, is there an issue for yuidocs accessible from github yet?

**Comment by mandragorn** [comment]
#128 (just created it)

**Comment by kentmw** [comment]
Add after https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/collectionRegistrationMixin.js#L86
```
  parentInstance.add(model);
```
