### ISSUE TITLE
collection.registerIds should push existing models previously fetched to requester collections

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#126]
Currently, there's no way to "pull" models from a cache collection into a requester collection. You can track ids and any updates or future pulls will be pushed to the requester collection. But, besides doing a full "fetch" call on the requester collection that also does an ajax server call, you can't just ask the cache for the models it already knows about. I think when you call trackIds, it should add to the requester models that the cache already has.

**Comment by kentmw** [comment]
Interestingly, trackIds _removes_ old models, but does not try to get new models from the cache. This leaves the requester in a strange state of having the collection in a half-updated state.

**Comment by mandragorn** [comment]
+1 - agreed and there should be a method or option where it doesn't fetch anything if everything is already in the cache (I think this is covered by #124)

**Comment by kentmw** [comment]
We should add
```
  pullByIds: function(newIds) {
    this.trackIds(newIds);
    return this.pull();
  }
```
NOTE: this requires #124 to be done first


perhaps we should update the naming convention of fetchByIds and pullByIds to registerAndFetch and registerAndPull
