### ISSUE TITLE
Add null check to collectionRegistrationMixin.js

### ISSUE THREAD

**Issue by matt-peairs** [vecnatechnologies/backbone-torso#132]
The function collection.registerIds throws an error when it tries to get storedIds.length and storedIds is undefined. This can cause the page to become non-responsive.

I added a check to bypass this problem. See: https://github.com/vecnatechnologies/backbone-torso/pull/131

**Comment by matt-peairs** [comment]
I also added a pull request on the 0.1.x branch: https://github.com/vecnatechnologies/backbone-torso/pull/133

**Comment by mandragorn** [comment]
Fixed by #131 and #133
