### ISSUE TITLE
How does a parent view inject other views that are not instantiated by the parent

### ISSUE THREAD

**Issue by mandragorn** [vecnatechnologies/backbone-torso#135]
As a developer I would like to inject a global view (one that isn't instantiated by the parent) when the parent renders.  But this view should not be disposed when the parent is disposed since its lifecycle is broader than the parent.

For example the parent view is a perspective and the global view is the footer.  The footer view I want to use on a bunch of different perspectives so I only want to instantiate it once.  That said, I don't want the view to be disposed if the parent view is disposed (since I will want to attach it to the next perspective).

**Comment by kentmw** [comment]
+1

**Comment by xzhang1217** [comment]
Nice, looks good to me!
+1!

**Comment by mandragorn** [comment]
merged into 0.1.x and master.
