### ISSUE TITLE
Separate npm install and npm prepublish

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#14]
Right now npm install builds the code needed to publish. However, npm install is run on projects to get the post-published code. Therefore, we need to separate the concept of "npm install"-ing the code (which will be run for everyone using the code) and building the code before publishing - which happens while dev'ing on Torso

**Comment by mandragorn** [comment]
I'm not sure I understand, there currently isn't any pre-publish or install scripts setup in the package.json.

**Comment by kentmw** [comment]
This is true. I don't mean separating actual scripts - just that we need to separate what's functionally happening when you run npm install.

**Comment by kentmw** [comment]
I can't replicate this issue. Maybe I was wrong, or maybe the npm prepublish fixed it.

**Comment by mandragorn** [comment]
this may have been an old issue while I was working things out in the build process.  At one point I had install tied to a script in package.json.
