### ISSUE TITLE
What's the justification for using "Cell" instead of "NestedCell" as the default viewState in a torso view?

### ISSUE THREAD

**Issue by Earthstar** [vecnatechnologies/backbone-torso#143]
It seems like the ability to listen to events on nested properties is always desirable to me, so I don't understand why we wouldn't just use NestedCell everywhere.

**Comment by kentmw** [comment]
We would always use NestedCell and NestedModels if they didn't bring large overhead with them. For simple, small applications, Nested objects are probably fine, but if you have many objects (not sure the exact number but probably >100) that are updating nested properties with views that listen to changes, things get slow quickly.

It was a matter of choice for speed rather then functionality. You can switch it if you want by doing:
```
this.viewState = new NestedCell();
```
in your initialize method.

**Comment by Earthstar** [comment]
Okay, I see that in the documentation now.
