### ISSUE TITLE
Write documentation for Torso's View lifecycle

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#16]

**Comment by kentmw** [comment]
@mandragorn, can you add the documentation from Vecna's question/answer section of torso's view lifecycle here?

**Comment by stonecalvin** [comment]
I can get the docs, but I am not sure what you are referencing.

**Comment by kentmw** [comment]
Done. http://tonicdev.com/kentmw/torso-view-lifecycle
