### ISSUE TITLE
Move Feedback Design to the documentation on this site

### ISSUE THREAD

**Issue by mandragorn** [vecnatechnologies/backbone-torso#177]
Lots of good examples, pdf export:
[SW-FeedbackDesign-120116-1344-166.pdf](https://github.com/vecnatechnologies/backbone-torso/files/87808/SW-FeedbackDesign-120116-1344-166.pdf)

**Comment by kentmw** [comment]
Feedback documentation is now in tonicdev and is more up-to-date than the pdf.

**Comment by kentmw** [comment]
For the record: http://tonicdev.com/kentmw/torso-view-feedback
