### ISSUE TITLE
Error when initializing Form View

### ISSUE THREAD

**Issue by Earthstar** [vecnatechnologies/backbone-torso#185]
I'm getting an error when initializing a form view. This error is caused because FormView.constructor calls InitializedFormView.initialize before this.fields has been initialized. InitializedFormView.render calls FormView.delegateEvents() which eventually calls FormView.__getFieldOptions().

There are several options I see for resolving this bug:

1. Move the field initialization to above View.apply
2. Modify __getFieldOptions such that it runs even if this.fields isn't initialized.

What is the justification for having the call to View.apply(this, arguments) be in the middle of FormView.constructor?

**Comment by Earthstar** [comment]
See https://github.com/vecnatechnologies/backbone-torso/pull/186

**Comment by pepperbc** [comment]
I ran into the same issue, and came to the same conclusion. I couldn't find any negative side effects by moving View.apply to the bottom of the constructor.
