### ISSUE TITLE
FormView model for selected option does not always get updated

### ISSUE THREAD

**Issue by pepperbc** [vecnatechnologies/backbone-torso#187]
Example: 

        <select {{bindModel 'serviceType'}}>
          <option value="{{defaultOptionValue}}">
            {{i18n "default"}}
          </option>
          {{#each serviceTypes}}
            <option value="{{id}}">
              {{name}}
            </option>
          {{/each}}
        </select>

The preceding code iterates over the "serviceTypes" collection, creating an option for each item. If this collection changes, the select/options are properly redrawn. If the currently selected option is removed from the collection, the first option in the select is selected, but the form model is not updated with the  value of this option.

Repro steps:
1. Create a formView with a select with options backed by a collection
2. Bind model.selectedItem to the select
3. Select an item from the dropdown
4. Remove the selected item from the backing collection
5. The top item of the select is now selected
6. model.selectedItem should have the value of the top item, but still has the value of the deleted item

**Comment by kentmw** [comment]
Does this have anything to do with #176 or #84

**Comment by pepperbc** [comment]
I think it's a separate issue - it's possible it may be fixed when #84 is done, but not certain.
