### ISSUE TITLE
Remove "super" from views and collections

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#19]
Figure out a better design pattern then having to call "super" during initiailization

**Comment by mandragorn** [comment]
+1 - using super breaks normal lint checkstyle rules, this causes problems every time we try to setup lint on a project using Torso (super is a reserved word in strict mode).

**Comment by kentmw** [comment]
Super is gone from Views but not collections but seeing as #62 and #63 handle collection super's I will close this as duplicate
