### ISSUE TITLE
Refactoring requester/private collection fetch and pull related methods

### ISSUE THREAD

**Issue by blakejwc** [vecnatechnologies/backbone-torso#190]
The naming of the methods 'fetchByIds' and 'pullByIds' should be improved.  Kent suggested fetchByIds and pullByIds be changed to something like trackAndFetch and trackAndPull.

Additionally, the 'fetch', 'fetchSubsetOfTrackedIds', and 'pull' methods for the requester/private collection share very similar logic for forcing the parentInstance to fetch and should be broken out.

**Comment by kentmw** [comment]
I can update this. Is trackAndFetch and trackAndPull good enough to warrent a change from fetchByIds and pullByIds whose logic consists of tracking their ids and performing a fetch/pull
