### ISSUE TITLE
calling fetch on a private collection when a tracked id is repeated passes the non-unique list to the server.

### ISSUE THREAD

**Issue by mandragorn** [vecnatechnologies/backbone-torso#191]
`this.privateCollection.fetchByIds([1, 1, 1])` will hit the /ids endpoint on the server with [1, 1, 1] instead of [1].

**Comment by mandragorn** [comment]
this was only a problem because the server bombed out when they were not unique.  Both sides (server and torso) should probably be fixed in this case.  I'm not sure if there are other repercussions when tracking the same id multiple times.

**Comment by kentmw** [comment]
interesting. on one hand i want the to be controlled by the user. but on the other hand, this whole collection cache setup is supposed to make sure you only have one instance of an object on the page at a time, and if the server returns multiple instances... actually i think that backbone would merge models with the same id in the collection.

**Comment by mandragorn** [comment]
I guess if the ids are merged it doesn't matter.  I figured out how to handle it both server and client side w/o touching torso.

**Comment by kentmw** [comment]
Closing for now until we encounter a problem with this that we think should be dealt with by torso
