### ISSUE TITLE
Switch test browser environment from jsdom to Karma + PhantomJS 

### ISSUE THREAD

**Issue by Earthstar** [vecnatechnologies/backbone-torso#192]
The current test infrastructure with jsdom has some deficiencies:

- Doesn't run on windows
- Test setup isn't as straightforward as it could be
- Can only test in NodeJS environment, not actual browsers

Running the tests with Karma would eliminate these problems.

**Comment by arikwex** [comment]
Should #113 be closed in favor of this?

**Comment by kentmw** [comment]
+1 to this issue and lets close #113
