### ISSUE TITLE
Redefining a FormView's FormModel in the initialize method needs event listening cleanup

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#210]
You can't redefine a FormView's FormModel in the initialize method without also redefining the this.listenTo(this.model, ...) blocks.

It seems like it would be better to define the this.listenTo(this.model ...) blocks after the View.apply - that way you can be sure the model is the correct form model before attaching listeners to it.

**Comment by mandragorn** [comment]
+1
