### ISSUE TITLE
IE not happy with document.activeElement call in hotswapKeepCaret when in an iFrame

### ISSUE THREAD

**Issue by maurag13** [vecnatechnologies/backbone-torso#219]
We currently have hotswapKeepCaret starting with this:

var currentCaret,
          activeElement = document.activeElement;

which works fine from iFrames in Chrome & Firefox, but not so much in IE (https://www.tjvantoll.com/2013/08/30/bugs-with-document-activeelement-in-internet-explorer/).  Needs a try/catch wrapped around the activeElement call.

**Comment by mandragorn** [comment]
fixed in #220
