### ISSUE TITLE
Look into peerDependencies as a potential for Backbone and jQuery

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#241]
Just saw peerDependencies were a thing in npm. I need to look into them to see if they're something we could use for Backbone and jQuery which I think are peer dependencies.

**Comment by Earthstar** [comment]
Desired behavior: Torso does not bring in its own jQuery, etc. dependency when installed in another project. 

Based on some research, I think simply adding jQuery as a peer dependency will work. npm < 3 will automatically install jQuery. If we want to support npm > 3, we'd probably need to additionally specify jquery as a devDependency so Torso can continue to run tests.
