### ISSUE TITLE
release-it fails with missing unprefixed version

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#249]
It dies when I try to "release-it":

```
WARNING Probably the current version in package.json is not a known tag in the repository.
ERROR Could not create changelog from latest tag (0.6.5) to HEAD.
```

It's because the last release wasn't tagged ever as 0.6.5. @mandragorn, thoughts?

**Comment by mandragorn** [comment]
yea, I had to modify things to add the v to the tag since you were doing that before.  If we drop the v from the tag name the issues should go away.  The main reason I wanted to standardize by using release-it was to avoid the inconsistent tag names, etc.
