### ISSUE TITLE
Change api for overriding prepare()

### ISSUE THREAD

**Issue by pepperbc** [vecnatechnologies/backbone-torso#252]
Currently when you override prepare(), you have to call the parent's prototype prepare(), which is difficult in the case of inheritance, and impossible in a mixin context. In general it's all a bit messy.

Proposal:

Change the signature of prepare() to prepare(context), where context is the present output of the default prepare method. The new default prepare would just be:

```
prepare(context) {
  return context;
}
```

Views could either overwrite or extend the passed in context.

**Comment by kentmw** [comment]
I definitely agree that we should make overriding prepare easier. But, I'd rather not have an argument because I think it would confuse people that they should pass in paramenters to the prepare method. We made it not take arguments at the beginning because we went down a rabbit hole of preparing different results by passing in arguments. We decided that prepare method was always just a reflection of the current state, and that arguments weren't needed.

That said, because prepare is really a private function, we could have the render method invoke `_prepare` that invokes a null op `prepare` (the one you override) and then just adds to it the view/model defaults using `_.defaults` which would only write it if someone didn't already specify the view or model fields.

**Comment by pepperbc** [comment]
Isn't prepare only called by torso internals, so that would be the only thing that would need to pass in the argument? The prepare method would still just be a reflection of the current state - the argument is just a way to do inheritance.

**Comment by kentmw** [comment]
It's a private method but it's not a torso private method. If someone overrides _updateDOM, there have been a number of times where people choose between templates or reinvoke `this.templateRender(this.$el, this.template, this.prepare());` I don't want to make it hard for someone to invoke `this.prepare();`

**Comment by mandragorn** [comment]
another option is we don't pass it in, but merge it for you.

if you define _prepare() then prepare() will return: 
`_.extend(View.prototype.prepare.apply(this), this._prepare())`

**Comment by kentmw** [comment]
I like Josh's twist on this.

**Comment by kentmw** [comment]
How about:
```
prepare: function() {
  var context = { ... };
  return this._prepare(context);
}

_prepare: function(context) {
  return context;
}
```

**Comment by mandragorn** [comment]
:+1:

**Comment by arikwex** [comment]
```
var BASE = Backbone.View.extend({
  constructor: function() {
    this.value = 123;
  },

  prepare: function() {
    return {
      baseContext: this.value
    }
  }
});

var CHILD = BASE.extend({
  constructor: function() {
    this.value = 456;
  },

  prepare: function() {
    var ctx = BASE.prototype.prepare.apply(this);
    ctx.childContext = 789;
    return ctx;
  }
});

var inst = new CHILD();
inst.prepare();
```

The trick obviously being "BASE.prototype.prepare.apply(this);"
When you "inherit" from a base class, you are quite aware of who your parent class is... so why be ashamed to refer to it again in the same file?

(Am I missing something here?)

**Comment by kentmw** [comment]
Sup sup @arikwex. That's how we are and have been doing prepare methods. We probs have 100's of prepare methods exactly like you've shown. Just curious if there's an easier way to add to the context without have to "override" the prepare method everytime.

**Comment by arikwex** [comment]
But... it's... like... one line :(

**Comment by kentmw** [comment]
When you think about a parent vs. child relationship, you're right. But the 90% use case is extending the Torso.View.

Torso.View's prepare method right now:
```
    prepare: function() {
      if (this.model) {
        return {
          model: this.model.toJSON(),
          view: this.viewState.toJSON()
        };
      } else {
        return {
          view: this.viewState.toJSON()
        };
      }
    },
```

In order to just create a basic top-level Torso view I have to override the base Torso.View:

```
var BASE = Torso.View.extend({
  prepare: function() {
    var context = Torso.View.prototype.call(this);
    context.foo = 1;
    return context;
  }
});
```

I'd like to simplify the top-level view so that it looks like your BASE

**Comment by arikwex** [comment]
Then modify the extend method to perform prototype chaining XD

**Comment by arikwex** [comment]
I'll buy you a beer if you do.

**Comment by kentmw** [comment]
@arikwex have you taken a look at [super](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super) yet?

**Comment by kentmw** [comment]
Here's my 30 minute stab at that:
```
// redefine backbone extend
var extend = function(protoProps, staticProps) {
    var parent = this;
    var child;

    if (protoProps && _.has(protoProps, 'constructor')) {
      child = protoProps.constructor;
    } else {
      child = function(){ return parent.apply(this, arguments); };
    }

    _.extend(child, parent, staticProps);

    child.prototype = _.create(parent.prototype, protoProps);
    child.prototype.constructor = child;

    child.__super__ = parent.prototype;

    ///////// MY CODE /////////
    _.each(child.prototype, function(value, key) {
      if (_.isFunction(value) && _.isFunction(parent.prototype[key])) {
        child.prototype[key] = function() {
          var args = Array.prototype.slice.call(arguments);
          // Add parent "super" method to end of arguments array
          args.push(parent.prototype[key]);
          value.apply(this, args);
        }
      }
    });
    child.prototype.getSuper = function(args, bind) {
      var superMethod = args[args.length - 1];
      if (bind) {
        // Bind arguments to the super method.
        var boundArgs = Array.prototype.slice.call(args);
        boundArgs.pop(); // remove super method
        boundArgs.unshift(superMethod, this);
        console.log(boundArgs);
        return _.bind.apply(null, boundArgs);
      }
      return superMethod;
    }
    // END MY CODE
    return child;
  };
```

```
var MyView = Torso.View.extend({
  prepare: function(super) {
    var context = super();
    context.foo = 1;
    return context;
  }
});
 
// or you can use getSuper if you don't want to define "super" as an argument 
// or the arguments size is variable.

var MyView = Torso.View.extend({
  otherMethod: function(foo, bar, baz) {
    // pass in true to bind current arguments to super function.
    var result = this.getSuper(arguments, true)(); 
    result++;
    return result;
  }
});
```

Tested it and it works for the base cases:
```
var Test = Model.extend({print: function(test) {console.log('boo' + test);}});
var Foo = Test.extend({print: function(test) {this.getSuper(arguments, true)();console.log('foo' + test);}});
var foo = new Foo();
foo.print('Hello');
// console.log: 'booHello'
// console.log: 'fooHello'
```

**Comment by kentmw** [comment]
Without revisiting this issue at all to see what our past discussion was, I'd like to make a reactionary proposal to a failed attempt at overriding the prepare method:

```
  prepare: function(context) {
    context.myUpdates = 'my updates';
  }
```

By passing in the context, I don't have to remember to return anything and I can overwrite anything I want.

**Comment by kentmw** [comment]
From a brief conversation with @mandragorn, we just have to make sure this still works:

```
   prepare: function() {
     var context = Torso.View.prototype.prepare.apply(this);
      context.myUpdates = 'my updates';
     return context;
  }
```

**Comment by kentmw** [comment]
Added `_prepare` that takes in a context that you can add to, or you can return an object that will be merged (and take priority over) existing context.

**Comment by kentmw** [comment]
Also `prepareFields` is a short hand way to add things to the prepare context
