### ISSUE TITLE
torso-bundle.js is not version controlled

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#27]

**Comment by kentmw** [comment]
I think I understand why we have a bundle - for when someone want to just grab the bundle for global use. However, we .gitignore the bundle, which means someone has to pull the project and build the code in order to get it. I vote we either version control the bundle or move it to test

**Comment by mandragorn** [comment]
torso-bundle.js should be included when it is published to NPM.  So version controlling it makes sense as long as we have some way to make sure it is kept up to date since the build process will change it based on other files.
