### ISSUE TITLE
Using formViews for the items of a list view is complicated.

### ISSUE THREAD

**Issue by mandragorn** [vecnatechnologies/backbone-torso#270]
FormViews setup this.model as the form model.  List item views automatically set this.model to the list item's model.  It would be nice to use a form view directly without a lot of boiler-plate.

Simple Workaround: have 2 views, the list item view which owns a form view bound to its model.

Thoughts on fixes:
1. have FormView use this.model for anything that references the form model as long as it extends FormModel, otherwise use an alias this.formModel (this is to preserve backwards compat - using this.model as a form model could be deprecated).  Eventually switch to just using this.formModel to reference the form model so that FormViews can have this.model reference actual object models.
2. Change list item views to set the model on an alternate property if this.model already exists.

**Comment by kentmw** [comment]
`options.modelName` can change the property name that the object model is set in the item view. Change that to something other than `model` and it should not conflict with the the form model's `model`

**Comment by kentmw** [comment]
My previous comment and the existence of #175 should be enough to close this issue
