### ISSUE TITLE
Perspectives with Unique Models

### ISSUE THREAD

**Issue by SBShane** [vecnatechnologies/backbone-torso#283]
First off I want to say that backbone-torso looks very promising. I came across it while trying to figure out elegant solutions to some of the problems I was having with Backbone. I've started using it for a project even though I know it's not finished yet.

That said, this isn't an issue, but more of a question. In the torso generator, I see that all perspectives are returned as essentially singletons. Which is great because if I leave the perspective and them come back to it, everything is still there. But I'm having trouble figuring out the best way to handle a common scenario:
A ListView that links to a DetailView where each DetailView contains a unique model (or just its id) and therefore unique information. Some solutions I see are:

A.
DetailView doesn't return/export a singleton. This would allow me to initialize the view from Router with the unique model. This is the common approach for Backbone. But this then complicates the switchPerspective method because now I need to check whether the View is already initialized and handle it differently. Additionally, I also have to modify the switchPerspective method further to dispose of this view instead of just detaching it.

B.
Attach a ChildView to DetailView from Router that contains the unique model. While this works, this seems to not be recommended. Only DetailView should be aware of it's child views.

C.
Add a setModel to DetailView. This seems to align with how ListView works with setCollection. After the Router switches perspectives, the Router calls this.current.setModel with the new model. I would have to implement setModel similar to setCollection to stop listening to the previous model.

Option C seems to me to be the preferred way to handle this, but wanted to see if you already had an elegant way of handling this scenario or what you would recommend.

**Comment by kentmw** [comment]
I'm still trying to hone in on what the relationship between DetailView and ListView is. A ListView is usually backed by a Collection of Models or Cells (if the model isn't persisted). ItemViews are generated as soon as the collection adds/reorders/removes a model/cell. Is your DetailView acting as the ItemView? If it is, the DetailView will be seeded with the model/cell as `this.model`

**Comment by kentmw** [comment]
On a larger note, Perspectives should be singletons if you want to maintain view state - like you said, when you move between them, you want to save information about the view. A Perspective is like a webpage and typically you only need one instance of that. However, a View can always be a non-singleton if you need more than one instance. You'll just have to manage its lifecycle - attached or not, active or not, and finally to dispose of the view. For ListView's, the lifecycle is managed totally autonomously - relying on the presence of a model inside the Collection to determine the lifecycle of the ItemView

**Comment by SBShane** [comment]
I see. So from the router, I wouldn't always call switchPerspective from a route method. If I need to load a view that's not a singleton, I would just implement custom code for handling that. The scenario I'm trying to explain is this:
```
var AppRouter = Torso.Router.extend({
    current     : null,
    
    routes :
    {
        ''            : 'home',
        'detail/:id'  : 'detail'
    },
    
    /**
      * Stop the history if it's already started, bind the routes, and then
      * start the history.
      */
    start : function(options)
    {
        Torso.history.stop();
        this._bindRoutes();
        Torso.history.start(options);
    },
    
    home : function()
    {
        console.log('Home Route');
        
        this.switchPerspective(require('./views/homeView'));
    },
    
    detail : function(id)
    {
        console.log('Detail Route');
        
        this.switchPerspective(require('./views/detailView'));
    },
    
    /**
     * Switches the current perspective to be the given perspective
     */
    switchPerspective : function(nextPerspective)
    {
        if(this.current)
        {
            this.current.detach();
        }
        
        this.current = nextPerspective;
        this.current.attachTo($('.app'));
    }
});
```

What is the best way to pass the id for the detail route into the DetailView? Using switchPerspective, I cannot simply initialize DetailView with the id as is commonly done because it's a perspective/singleton.

So my options are:

A. 
```
detail : function(id)
{
    // DetailView does not return singleton
    var DetailView = require('./views/detailView');
    var detailView = new DetailView({
        id : id
    });
    
    // This is simplified just for this example. Since I'm now I'm responsible for disposing of this view,
    // this would be a little more complicated.
}
```

B.
```
detail : function(id)
{
    this.switchPerspective(require('./views/detailView'));
    
    this.current.setId(id);
}
```
In example B, setId is a method on DetailView that does the following:
```
setId : function(id)
{
    this.stopListening(this.model, 'change', this.render);
    
    this.model = new DetailModel({
        id : id
    });
    
    this.listenTo(this.model, 'change', this.render);
}
```

It just seemed like there may be an easy way that I wasn't seeing to pass the id to DetailView. ListView has the 'setCollection' method that handles the  boilerplate of removing the collection listeners and re-implementing them. So I thought there may be something similar that would allow me to pass variables (or a model) to a perspective without having to handle code cleanup myself. I'm using example B for now, but wanted to know if you would do it differently. It's such a common scenario to need to pass a route variable to a view and I got hung up on it for a while trying to decide the best way to handle it. I could see others getting hung up as well. Maybe it would be helpful to include an example in the documentation of how you would pass a route variable to the perspective.

**Comment by kentmw** [comment]
Your way totally works. There are some nuances that would help make your code more extensible, but for simple cases, choice B works. 

Here's what I would do:

If your model is going to be used by any other "player" (e.g. another view, a service, etc.) then the Model should be in a cache (which is basically an accessible instance of a Collection)

detailCache.js
```
var DetailModel = require('./DetailModel');

module.exports = new (Torso.Collection.extend({
  model: DetailModel,
  getOrCreate: function(id) {
    return this.get(id) || this.create({id : id});
  }
}))();
```

detailPerspective.js
```
var DetailView = require('./DetailView');
module.exports = new (Torso.View.extend({
  initialize: function() {
    this.detailViews = {};
  },
  setDetailView: function(id) {
     this.currentDetailsView = this.detailsView[id] || new DetailView({id: id});
     this.detailsView[id] = this.currentDetailsView;
  },
  attachTrackedViews: function() {
    this.attachView('my-details-view', this.currentDetailsView);
    // just add an injection site <div inject="my-details-view"></div>
   }
}))();
```

DetailView.js
```
var detailCache = require('./detailCache');
module.exports = Torso.View.extend({

  initialize: function(opts) {
    this.model = detailCache.getOrCreate(opts.id);
  }
});
```
router.js
```

var AppRouter = Torso.Router.extend({
  
  ...
  detail : function(id) {
   var detailPerspective = require('./detail/detailPerspective');
   detailPerspective.setDetailView(id);
   if (this.current != detailPerspective) { // really, an unneeded step, but I do it anyway.
     this.switchPerspective(detailPerspective); 
    }
  }
});
```

**Bonus**: use the event bus to do the update for you.

router.js
```
var bus =Torso.Events;
var AppRouter = Torso.Router.extend({
  ...
  detail : function(id) {
   bus.trigger('new-detail', id);
   this.switchPerspective(require('./detail/detailPerspective')); 
  }
```
detailPerspective.js
```
var DetailView = require('./DetailView');
module.exports = new (Torso.View.extend({
  initialize: function() {
    this.detailViews = {};
    this.listenTo(bus, 'new-detail', this.setDetailView);
  },
  ... //same as before
}))();
```

So, the benefits of this: 
1. Having a singleton perspective for all detail views, allow you to target what actually changes by updating the DetailModel while keeping things like header, footer, other views the same.
2. Each DetailView can handle its own view state and is persisted across moving between routes.
3. Using a cache to grab the model allows you to use the single instance of the model anywhere in your code which helps to maintain the "truth" of your objects (don't want multiple instances of a model that can be updated in different spots of the app)
4. You don't have to refetch the model if you've already brought it in once.

I try not to redefine a model on the view. In Torso, you totally can do it, but often times I find that it's better to have a new instance of a view if I want to show different models.

**Comment by kentmw** [comment]
Sorry, I made a number of updates to the last post. Should be good now.

**Comment by SBShane** [comment]
Kent, this is fantastic!! Thank you. I had come across the cache mixin while reading over the library, and I understood what it should do, but didn't know how to implement it since it hadn't been covered in the documentation yet. I was planning to revisit later, but this gives me what I was looking for to get started.

And the dictionary of child views is something I would have NEVER thought of, but its brilliant. I will be using all of these recommendations. Thanks for taking the time to show me how you would do this. Its extremely helpful!

**Comment by kentmw** [comment]
@SBShane we're pretty close to getting the first official release out. I'm looking to help people adopt it, which means I'm very open to answering questions and working through problems with you. Feel free to reach out. Post an issue or email me at kentmw@mostlyepic.com
