### ISSUE TITLE
DataBehavior does not auto-render view when data is fetched

### ISSUE THREAD

**Issue by mandragorn** [vecnatechnologies/backbone-torso#306]
It is specified in the specs but... yea... didn't happen.

See 2nd bullet point under goals here: https://github.com/vecnatechnologies/backbone-torso/blob/master/docs/modules/behaviors/DATA_BEHAVIOR.md

The workaround is to add a manual listener:
```
    var billDataBehavior = this.getBehavior('bill');
    this.listenTo(billDataBehavior, 'fetched', this.render);
```

**Comment by mandragorn** [comment]
Worth adding a flag to turn this off for the cases where rendering happens to be costly.  By default it should render every fetch complete.

**Comment by kentmw** [comment]
I was going to say the exact same thing. I'm torn about what should be
default. But it's an easy thing to flip if we find out we got it wrong

**Comment by mandragorn** [comment]
going to start working on this.  Will default to... not rendering by default to keep it consistent with current behavior.
