### ISSUE TITLE
DataBehavior trackids fails if it returns undefined.

### ISSUE THREAD

**Issue by mandragorn** [vecnatechnologies/backbone-torso#308]
https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/behaviors/DataBehavior.js#L255

if ids is undefined there, then it should default to an empty array... possibly __getIds() should never return undefined.

**Comment by kentmw** [comment]
@mandragorn is line 255 still correct?

**Comment by mandragorn** [comment]
my guess is that it moved to https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/behaviors/DataBehavior.js#L251

**Comment by mandragorn** [comment]
line 251 is no longer correct either :(
