### ISSUE TITLE
DataBehavior shouldn't trigger a fetch if ids returns undefined and the collection currently empty

### ISSUE THREAD

**Issue by fyliu24** [vecnatechnologies/backbone-torso#336]
https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/behaviors/DataBehavior.js#L508
https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/behaviors/DataBehavior.js#L524

When normalizedIds is undefined, it returns a promise with empty array of ids which will trigger a trackAndFetch of empty ids and then a fetchSuccess call which will trigger 'fetched'.
https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/behaviors/DataBehavior.js#L253
https://github.com/vecnatechnologies/backbone-torso/blob/master/modules/behaviors/DataBehavior.js#L258

When a view is initializing, the data behavior on it is triggered when the ids is usually still undefined. This shouldn't trigger a 'fetched' event. Since it's technically not fetching anything.

**Comment by mandragorn** [comment]
@fyliu24 do you have an example of this that I can test against and the desired outcome?
