### ISSUE TITLE
add application level prepare data

### ISSUE THREAD

**Issue by mandragorn** [vecnatechnologies/backbone-torso#347]
add application level prepare definition that will add app data to the prepare of every view.

We have quite a bit of app data that we have to add to a large number of views.  Would be nice to define this in a single place and have it added to the template context of every view.

**Comment by kenclary** [comment]
I think the most Torso-canonical way to do this is:

- Near the beginning of render (before the prerender hook), create a this.renderState model
- In prepare, add renderState.toJSON to the context, probably as 'render' (parallel to 'model' and 'view')
- after the postrender hook, set it to null or such.

With that, anyone can add things to it in prerender (and perhaps read off it in postrender), and thus put render-specific things in the context without overriding prepare.

(It might be useful, though less canonical, to allow the renderState model to persist outside of rendering, and be manipulated at any time, by events and whatnot. However, at that point you might as well use viewState.)

**Comment by mandragorn** [comment]
we can also add a Torso.appState cell who's toJSON() gets added in View's prepare.

How is renderState different from viewState that you update in preRender?
The only gap is being able to add arbitrary models to the view's prepare().

**Comment by mandragorn** [comment]
Current View Prepare for reference:
```
    prepare: function() {
      return {
        model: this.model.toJSON(),
        view: this.viewState.toJSON(),
        formErrors: (_.size(this._errors) !== 0) ? this._errors : null,
        formSuccess: this._success
      };
    },
```

**Comment by kenclary** [comment]
> How is renderState different from viewState that you update in preRender?

Presumably, it is different because it being destroyed outside of each render call. (I have been told it is not Torso best practice to do, say, this.set('arrayData', this.someCollection.toJSON()), because it duplicates data. :)

Ergo, adding this.renderState.set('arrayData', this.someCollection.toJSON()) would get around persistent data duplication, without needing to override prepare.

Simply updating viewState in prerender (or any other context) works just fine for this, if one ignores the data duplication issue.

**Comment by mandragorn** [comment]
Potential new prepare:
```
__defaultModelsToExpose: ['viewState', 'model'],

prepare: function() {
  var modelsToExposeList = _.result(this, '__modelsToExpose');
  modelsToExposeList = _.union(modelsToExpose, this.__defaultModelsToExpose);
  var templateContext = {};
  if (modelsToExposeList && modelsToExposeList.length > 0) {
    for (var modelIndex = 0; modelIndex < modelsToExposeList.length; modelIndex++) {
      var modelName = modelsToExposeList[modelIndex];
      var modelToExpose = _.result(this, modelName);
      templateContext[modelName] = modelToExpose.toJSON();
    }
  }
  templateContext.formErrors = (_.size(this._errors) !== 0) ? this._errors : null;
  templateContext.formSuccess = this._success;
  return templateContext;
},
```

**Comment by mandragorn** [comment]
The prepare above would work equally well for collections or anything that defines a toJSON() method.

**Comment by kenclary** [comment]
That could work nicely.  (Note, in templates, references to `view` would need to be changed to `viewState`, which will mess with backwards compatibility.)

**Comment by mandragorn** [comment]
fixed

**Comment by kentmw** [comment]
i like having a cell on the router or main app module with state of the application accessible to the view. But as much as i'd like that as a default, i don't want to make a view require the router by default.

While I don't like the added complexity in the prepare method, allowing you to specify cells to add to the prepare method is kind of nice

**Comment by mandragorn** [comment]
for app state I was thinking of having Torso.appState that is independent of the router - just a raw singleton cell.

Will update comment with prepare with it.

**Comment by mandragorn** [comment]
it is an optional cell that you can add stuff to for the global app state.

**Comment by kentmw** [comment]
I'm not a huge fan. Mostly because it restricts Torso with a single instance of app state and because we've made Torso stateful.

The non-coding way to do this is to create a behavior with a prepare method that drops in a reference to an application-defined, application-level cell. Then when people want access to this, they drop in the behavior

**Comment by mandragorn** [comment]
Do we want to provide one in torso or let that up to the app developer?

**Comment by kentmw** [comment]
I'd prefer we leave default dependencies of the view to a minimum. Meaning, if we want an application-level, default cell on the View, we do one of two things:
1. Give a recipe for how to do that. Either by using a behavior, or improving the ease of adding things to prepare (we should do this anyway) and showing them how to add an app-level cell
2. Have a View request an app state cell non-intrusively/indirectly, that either returns null if the app creator hasn't set one up yet, or returns the cell if it has created one. Not exactly sure how you do this with non-optional requires. I tried thinking of a few examples of how to do this and didn't like any of them

**Comment by mandragorn** [comment]
ok, I updated the prepare above.  I'll probably do that now so we can include that in the next release.  Unless people have more comments on it.

**Comment by kentmw** [comment]
make `__modelsToExpose` not hidden and renamed so people know it's about prepare.

`modelsForPrepare` or `prepareModels` or `prepareCells`

Though, this will be an array so defining it on a view class level isn't particularly helpful. It does allow us to specify this.prepareModels = [appStateCell, myOtherCell, this.feedbackCell, ...]

**Comment by mandragorn** [comment]
I was going to make them not the models themselves, but the name of the model property on the view.

**Comment by mandragorn** [comment]
since we need a key to use in the context anyway the model name / view property can act as both key in the template context and make it so it can be defined on the class level.

**Comment by kentmw** [comment]
Ah, I like that minus the fact that the original app state object will have to be added onto the view instance. Small price I guess

**Comment by mandragorn** [comment]
we could duck type String vs Object to allow you to specify a global instance.

**Comment by kentmw** [comment]
then how about `prepareFields`, grab them off the view and do a toJson is there is one, otherwise just add the object itself

**Comment by kentmw** [comment]
yea, that could work. I approve

**Comment by mandragorn** [comment]
that works better.  I'll put a patch set up soon so we can discuss more.

**Comment by kentmw** [comment]
Some good stuff
