### ISSUE TITLE
Consolidate syntax for data-model and data-feedback

### ISSUE THREAD

**Issue by beiyi0207** [vecnatechnologies/backbone-torso#364]
Currently we have to use two different syntax's inside one field for objects:
`data-model="foo.bar"` and `data-feedback="foo[bar]"`
and the helper generates different prefixes depending on if the value is a number or string -123 or _foo.

As a developer, I want to use the same syntax for `data-model` and `data-feedback`, and I want to see the same prefixes regardless whether the value is a number or a string.

**Comment by mandragorn** [comment]
@beiyi0207 is this issue resolved?  If so then click the [close] button on the issue so we know it is addressed.  Thanks!

**Comment by beiyi0207** [comment]
Resolved.
