### ISSUE TITLE
Allow upgrades to versions of jquery >= 2.2.0

### ISSUE THREAD

**Issue by mandragorn** [vecnatechnologies/backbone-torso#371]
Figure out why 2.2.0 breaks torso tests and fix them.  Then widen the range of jquery versions.

**Comment by kentmw** [comment]
Due to https://github.com/vecnatechnologies/backbone-torso/pull/377, we don't need to widen the range of versions, but we do need to make our usages of jquery (or $) to work with later versions of jquery

**Comment by kentmw** [comment]
version of jquery-mockjax was behind and updating it required small tweaks to the import. Works now
