### ISSUE TITLE
Add ability to add url to Form model

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#5]

**Comment by kentmw** [comment]
Dealing with deactivating instead of disposing views

**Comment by kentmw** [comment]
This issue needs a description of what the issue is and what adding the url will do

**Comment by kentmw** [comment]
I think that maybe the Form Model url would be on save, and rather than pushing to each persisted Model, the flow would look like this: FormModel.save() -> pushes all data to server at FormModel.url. The server then performs a transactional change on all the models. If successful, a response would be sent to the FormModel and then passed to the persisted models. If unsuccessful, the server would not have updated any models, and the rejection would be passed to the FormModel who would show an error to the user and the persisted models would not be touched.

This would be great for transactional changes needed across multiple persisted models. The way it works now is that the FormModel pushes changes to each persisted model and calls save on them. If any fails, the FormModel attempts to push back the original model data to all the successful models and resaves. The hope is that at the end, all the models are back to their original state, but one of the successful models could have been updated in the time period of rolling back. This opens opportunity for rolling back to stale data or worse, the rollback push fails.

The bad thing about moving to the FormModel pushing to the server is that it requires a separate endpoint. My vote would be to have the programmer chose a separate url for transactional, multi-model pushing. Otherwise it delegates to each persisted model's url.

**Comment by mandragorn** [comment]
that makes sense to me.

**Comment by kentmw** [comment]
Done like how I proposed.
