### ISSUE TITLE
InitializeCallback

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#61]
Between constructing the view fields and the render/active calls, we'd like to be able to have view-specific logic and setup. Either we need a callback in-between or we need to intercept initialize from backbone and do torso setup there

**Comment by arikwex** [comment]
As per our discussion, we could use the notation:
initialize --- a method that should be invoked
_initialize --- a callback method that should be overridden by extensions

same for: activate, deactivate, dispose...

**Comment by kentmw** [comment]
changing to constructor to preserve backwards compatability
