### ISSUE TITLE
When using a FormModel to create new models, sometimes it doesn't push all values

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/backbone-torso#70]
I believe that it will push all the FormModel values to the model if the model contains NO values at all. But, if there are any defaults in the model (like @Class attributes), then it will default to just those properties.

Perhaps we can rework the logic so FormModel's work fine pushing to new object models without having to specify the fields it tracks.

**Comment by kentmw** [comment]
This is because of this line in __copyFields:
```
      if (!fields && this === origin) {
        fields = _.keys(destination.attributes);
      }
```
which assumes that if you leave the fields blank, and you are performing a push, you want to copy only the properties available in the destination which is the object model. In other words, a push will only push properties that exist on the object model. For pulls, it will pull all the object model values.

If we change this, or remove this conditional, we run the risk of pushing other object models' fields to the one tracking all the attributes. I.e. if you track all the fields on Object Model A and only a few in Object Model B, and you invoke a push, which fields are pushed to Object Model A? All of them? Including Object Model B? Including all the computed values? This is why we are currently trying to grab which attributes are Object Model A's by filtering on fields that are currently present on ObjectModel A. Which, of course, doesn't work if ObjectModel A is new and we're using the FormModel to create it.

Which leaves us with a couple of approaches:

1. Find out if a model is new and push all the properties if it is
2. Don't support unexplicit "all" properties when mutliple models are used

or I think what I'm leaning for:

```
      if (!fields && this === origin && _.size(this.__getAllModels(true)) == 1) {
        fields = _.keys(destination.attributes);
      }
```

which will only limit the pushed values if a model is traking all the properties and it isn't tracking another model - as is often the case when the form model is attempting to create a new object model. When using multiple models and tracking all the properties of one of them, then only push values currently existing in that model.

**Comment by mandragorn** [comment]
what if you want to remove a field in the object model by unsetting it in your form model?  Do you need to explicitly set it to `null` or `undefined`?

**Comment by kentmw** [comment]
When we're limiting the fields based on the existing properties in the object model, it will find the field in the object model you want to remove, and if the form model field is null, empty, undefined, or non-existent, it will set the object model's field as that.

If we aren't limiting as with the proposed setup when tracking all properties on a single model, then:
```
destination.set(this.__cloneVal(origin.attributes));
```
Which means that as long as the attribute entry exists on the form model (i.e. {foo: undefined} or {foo: null}, etc.)  then it will "remove" that property from the object model. If the form model doesn't have a reference to "foo" at all, then it won't change it on the object model.

I'm unsure as of now whether a form field that hasn't been touched but still bound to a form model property will set the value as null or have no reference at all.
