### ISSUE TITLE
[Question] Does ListView use the Torso Lifecycle by default. (Activate,Attach,detach,deactivate,dispose)

### ISSUE THREAD

**Issue by patrickckelly** [vecnatechnologies/backbone-torso#94]
I am currently trying to get ListView to adhere to the Torso Life-cycle. I can see that it activates within the constructor but I am unsure how to make the ListView attach,detach, deactivate.

**Comment by mandragorn** [comment]
note this is for the 0.1.9 version of torso since, as far as I can tell, 0.2.x has not been released.

**Comment by mandragorn** [comment]
@patrickckelly has this been resolved?  I think we figured this out with ListView not calling activate on initialize.

**Comment by kentmw** [comment]
When attaching child views, ListView does this manually by binding all the child view's dom fragments into one, and injecting this into the DOM. We should be concerned that attach (and therefor activate) is not invoked on child views.

**Comment by kentmw** [comment]
It also doesn't call plug and unplug :(

**Comment by kentmw** [comment]
Ran into problem with delegating events on child views because child views were not "attached"

**Comment by mandragorn** [comment]
Question is answered, if there are other issues create something new.
